### ISSUE TITLE
Problema con "url"

### ISSUE THREAD

**Issue by kabubi** [DanielRiera/phonegap-wordpress#1]
Cargue los datos en el index.js:

onDeviceReady: function() {
        app.receivedEvent('deviceready');
        wp_ini("www.rutadelaselva.com.ar","menu","categoria","post","123456789","debug");
    },

Pero aparentemente se duplica la "url"

http://puu.sh/iiB7c.png

"http://rutadelaselva.com.ar/app3/www.rutadelaselva.com.ar/wp-content/plugins/phonegap_connect/categorias.php Failed to load resource: the server responded with a status of 404 (Not Found)"

**Comment by DanielRiera** [comment]
Necesitaría ver el index.js entero para detectar un error, recordar que el archivo wp_connect.js no debe ser modificado.

**Comment by kabubi** [comment]
Gracias por la respuesta Daniel. El wp_connect.js esta tal cual lo descargue. Mi index.js esta aqui:
http://rutadelaselva.com.ar/app3/js/index.js
Saludos

**Comment by DanielRiera** [comment]
Añade a la URL delante http:// y también decirte que ese error es porque creo que lo estas ejecutando desde el navegador y debe ser en una aplicación emulador (Disponible en los Market de iOS y Android) o un dispositivo físico.

Prueba y me cuentas.

Un Saludo

**Comment by kabubi** [comment]
Listo, he agregado el "http://" y he quitado el "www", pero ahora el error es este:

Uncaught TypeError: Cannot read property 'appendChild' of null wp_connect.js:100

**Comment by DanielRiera** [comment]
No, el "www" dejarlo puesto, prueba y me dices y miro, hice un proyecto ayer con el plugin y no tuve problema.

**Comment by kabubi** [comment]
Si agrego el "www" me da el error de "access origin". Ya habilite mi cabecera y mi htaccess pero el error es el mismo:

XMLHttpRequest cannot load http://www.rutadelaselva.com.ar/wp-content/plugins/phonegap_connect/debug.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://rutadelaselva.com.ar' is therefore not allowed access.

**Comment by DanielRiera** [comment]
Descarga la app de Phonegap en tu móvil y pruebas. Si quieres deja tu Skype y hablamos para solucionarlo.

**Comment by kabubi** [comment]
Nunca he utilizado la app de phonegap. Por lo general la compilo en phonegap build.

**Comment by DanielRiera** [comment]
La compilación no tiene nada que ver con la aplicación que te digo, inicias el servidor estando en la carpeta raíz del proyecto ejecutas "phonegap serve".

Con la aplicación descargada pones la IP que te aparece en el terminal del servidor (ya que veo que lo tienes subido y no en local). Cuando conecte te aparecerá tu aplicación ejecutándose en el móvil a través de la aplicación de phonegap sin necesidad de compilar. Por el error de Access-orign comprueba el config.XML de tu proyecto.

**Comment by kabubi** [comment]
Listo, he logrado ejecutarla en el movil con la app the phonegap. Me muestra un alert con el nombre de mi web pero luego queda en "device is ready"

**Comment by kabubi** [comment]
Mi consola dice _api_/autoreload

**Comment by DanielRiera** [comment]
Eso es que se esta recargando pero es lo normal, tienes que ver en la App que se muestre y si esta en modo debug te lanzara un alert con el nombre del sitio de WordPress. 

Un Saludo, pero si sigues teniendo problemas puedes dejarme tu skype y hablamos por ahí mejor y mas rápido.

**Comment by kabubi** [comment]
Disculpa si te consulto por este medio, estoy en mi trabajo y no tengo skype. He quitado el "debug" del index.js:

wp_ini("http://www.rutadelaselva.com.ar","menu","categoria","post","123456789");

Debo quitarlo tambien del wp_connect.js?
Gracias

**Comment by kabubi** [comment]
He probado eliminando el parametro y la app queda ejecutandose en "device is ready" por siempre...
He probado poniendo el texto "modo" como parametro para que no sea igual a "debug" pero la app queda ejecutandose en "device is ready" por siempre...
Alguna idea?

**Comment by DanielRiera** [comment]
Tienes toda la estructura HTML en tu index.html? Es que sin ver el proyecto completo no se donde puedes tener el error, cuando tu pongas el modo como debug tiene que lanzar una alerta con el nombre del sitio de WordPress.

**Comment by kabubi** [comment]
El modo "debug" funciono perfecto, me mostro una alerta con el nombre de mi sitio. Al quitar el debug solamente me aparece "device is ready"
El codigo es el tuyo de ejemplo:
https://github.com/DanielRiera/phonegap-wordpress/tree/master/Aplicaci%C3%B3n%20Phonegap

**Comment by DanielRiera** [comment]
Prueba esto, en el wp_connect.js borra el contenido de la última función porque puede que haya un problema ahí, tengo que revisarlo y lo volveré a subir pero prueba eso, borra el contenido de la ultima función y dejala en blanco y me cuentas.

**Comment by kabubi** [comment]
Ha funcionado. Pero al querer entrar en algun post me muestra un alert "Error en Post".
Desconozco como funciona la app de phonegap pero es normal que se vea la app como en la imagen?

http://puu.sh/iiS8Z.jpg

**Comment by DanielRiera** [comment]
Se ve correctamente, error en post es un error al obtener los post desde su sistema WordPress. Tendría que tener mas datos, pero por github es imposible poder verlo todo correctamente y arreglar posibles errores.

**Comment by DanielRiera** [comment]
Escribe a danielriera.p@gmail.com he intentamos solucionar los errores pero tiene que ser en unas horas que aquí en España son las 1:08 am
